version: '3.9'
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:
  pma-session-store:
services:
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=soregashi27
      - PMA_PASSWORD=soregashidegozaru
    ports:
      - 8080:80
    volumes:
      - pma-session-store:/sessions

  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - type: volumes
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
    environment:
      -
